services:
  snippets:
    container_name: "${SNIPPET_APP_NAME}"
    image: ghcr.io/snippetservices-group4/snippets-dev:latest
    environment:
      SPRING_APPLICATION_NAME: "${SNIPPET_APP_NAME}"
      DB_USER: "${SNIPPET_DB_USER}"
      DB_PASSWORD: "${SNIPPET_DB_PASSWORD}"
      DB_HOST: "${SNIPPET_DB_HOST}"
      DB_NAME: "${SNIPPET_DB_NAME}"
      DB_PORT: "${SNIPPET_DB_PORT}"
      SPRING_PORT: "${SNIPPET_SPRING_PORT}"
    ports:
      - "${SNIPPET_SPRING_PORT}:${SNIPPET_SPRING_PORT}"

  db-snippets:
    container_name: "${SNIPPET_DB_HOST}"
    image: postgres:15
    environment:
      POSTGRES_DB: "${SNIPPET_DB_NAME}"
      POSTGRES_USER: "${SNIPPET_DB_USER}"
      POSTGRES_PASSWORD: "${SNIPPET_DB_PASSWORD}"
    ports:
      - "${SNIPPET_DB_PORT}:5432"


  permissions:
    container_name: "${PERMISSION_APP_NAME}"
    image: ghcr.io/snippetservices-group4/permissions-dev:latest
    environment:
      SPRING_APPLICATION_NAME: "${PERMISSION_APP_NAME}"
      DB_USER: "${PERMISSION_DB_USER}"
      DB_PASSWORD: "${PERMISSION_DB_PASSWORD}"
      DB_HOST: "${PERMISSION_DB_HOST}"
      DB_NAME: "${PERMISSION_DB_NAME}"
      DB_PORT: "${PERMISSION_DB_PORT}"
      SPRING_PORT: "${PERMISSION_SPRING_PORT}"
    ports:
      - "${PERMISSION_SPRING_PORT}:${PERMISSION_SPRING_PORT}"

  db-permissions:
    container_name: "${PERMISSION_DB_HOST}"
    image: postgres:15
    environment:
      POSTGRES_DB: "${PERMISSION_DB_NAME}"
      POSTGRES_USER: "${PERMISSION_DB_USER}"
      POSTGRES_PASSWORD: "${PERMISSION_DB_PASSWORD}"
    ports:
      - "${PERMISSION_DB_PORT}:5432"


  parser:
    container_name: "${PARSER_APP_NAME}"
    image: ghcr.io/snippetservices-group4/parsers-dev:latest
    environment:
      SPRING_APPLICATION_NAME: "${PARSER_APP_NAME}"
      SPRING_PORT: "${PARSER_SPRING_PORT}"
    ports:
      - "${PARSER_SPRING_PORT}:${PARSER_SPRING_PORT}"

  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - 8000

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - react-app:/usr/share/nginx/html:ro
    depends_on:
      - react-app

  react-app:
    image: ghcr.io/snippetservices-group4/react-app-dev:latest
    container_name: react-app
    environment:
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    volumes:
      - react-app:/app:ro
